// <auto-generated />
using ApiRenato.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiRenato.Migrations
{
    [DbContext(typeof(DAOContext))]
    partial class DAOContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("ApiRenato.Model.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Renato",
                            Senha = "r3n4t0321",
                            Sobrenome = "Azevedo",
                            Usuario = "renatoads1"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Isabela",
                            Senha = "r3n4t0321",
                            Sobrenome = "Lacerda",
                            Usuario = "isabela321"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Julia",
                            Senha = "r3n4t0321",
                            Sobrenome = "Lacerda",
                            Usuario = "julia321"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
